### ISSUE TITLE
Drag position is not resetting after each swipe.

### ISSUE THREAD

**Issue by sioanis** [tumfoodery/react-toast-component#2]
**Describe the bug**
Drag position is not resetting after each swipe.

**To Reproduce**
1. Swipe 
2. Dismiss
3. Swipe again 
4. Drag position is not resetting

**Expected behavior**
Drag position should reset.

**Screenshots**
![bug](https://user-images.githubusercontent.com/3586765/66729553-22af8780-ee1a-11e9-8a4d-7396c69264ee.gif)

**Comment by cassioesp** [comment]
Hi @sioanis . May I take a look on this issue? :)

**Comment by sioanis** [comment]
Fixed
